package template

// layout provided by the initializer.
var layout = `
<!DOCTYPE html>
<html class="h-full">
<head>
  <title>{{.}}</title>
  
  <meta charset="utf-8" name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="csrf-param" content="authenticity_token" />
  <meta name="csrf-token" content="<%= authenticity_token %>" />

  <link rel="icon" href="/assets/images/favicon.png" type="image/png">
  <%= stylesheetTag("application.css") %>
  <%= javascriptTag("application.js", {defer: true}) %>
</head>
<body class="h-screen flex overflow-hidden bg-gray-100">
	<main>
		<%= yield %>
	</main>
</body>
</html>
`

// home page generated by the initialized.
var home = `
<h1>{{.}} Application</h1>
<p>This is a sample home page you can find in your source code. If you want to edit it go to <pre>/app/templates/home.plush.html</pre> file.</p>
`
