package templates

var (
	//DatabaseConfiguration is used to generate a copy of database.yml in the binary.
	DatabaseConfiguration = `
// this file was generated by X to be able to compile the 
// binary of the app.
package config

import (
	"strings"

	"github.com/gobuffalo/pop/v5"
)

var config = strings.NewReader(` + "`" + `
{{.Config}}
` + "`" + `)

func init() {
	pop.LoadFrom(config)
}`
)
